// Shared admin dashboard styles — matches existing dark theme + magenta accent

export const colors = {
  bg:      '#0a0a0a',
  card:    '#1a1a1a',
  input:   '#252525',
  border:  '#333',
  accent:  '#d946ef',
  white:   '#fff',
  muted:   '#aaa',
  dim:     '#555',
  error:   '#f87171',
};

export const statusColors = {
  pending_payment:    '#f59e0b',
  pending_acceptance: '#fb923c',
  accepted:           '#4ade80',
  in_progress:        '#60a5fa',
  completed:          '#888',
  cancelled:          '#f87171',
  refunded:           '#f87171',
  // payout statuses
  pending:            '#f59e0b',
  transferred:        '#888',
  failed:             '#f87171',
  // onboarding statuses
  approved:           '#4ade80',
  suspended:          '#f87171',
};

export const s = {
  page: {
    minHeight: '100dvh',
    background: colors.bg,
    display: 'flex',
  },
  sidebar: {
    width: '220px',
    background: colors.card,
    borderRight: `1px solid ${colors.border}`,
    padding: '24px 0',
    paddingTop: 'calc(24px + env(safe-area-inset-top, 0px))',
    display: 'flex',
    flexDirection: 'column',
    position: 'fixed',
    top: 0,
    bottom: 0,
    left: 0,
    zIndex: 100,
    transition: 'transform 0.25s ease',
  },
  sidebarBackdrop: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.6)',
    zIndex: 99,
  },
  mobileTopBar: {
    position: 'sticky',
    top: 0,
    zIndex: 50,
    background: colors.card,
    borderBottom: `1px solid ${colors.border}`,
    padding: '10px 16px',
    paddingTop: 'calc(10px + env(safe-area-inset-top, 0px))',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  hamburger: {
    background: 'none',
    border: 'none',
    color: colors.white,
    fontSize: '1.4rem',
    cursor: 'pointer',
    padding: '8px',
    lineHeight: 1,
  },
  sidebarLogo: {
    textAlign: 'center',
    padding: '0 16px 24px',
    borderBottom: `1px solid ${colors.border}`,
    marginBottom: '16px',
  },
  sidebarLogoText: {
    margin: '8px 0 0',
    fontSize: '1rem',
    fontWeight: 700,
    color: colors.white,
  },
  navLink: {
    display: 'block',
    padding: '10px 20px',
    color: colors.muted,
    textDecoration: 'none',
    fontSize: '0.9rem',
    fontWeight: 600,
    borderLeft: '3px solid transparent',
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    textAlign: 'left',
    width: '100%',
  },
  navLinkActive: {
    color: colors.accent,
    borderLeft: `3px solid ${colors.accent}`,
    background: 'rgba(217, 70, 239, 0.05)',
  },
  content: {
    marginLeft: '220px',
    flex: 1,
    padding: '24px 32px',
    paddingBottom: 'calc(24px + env(safe-area-inset-bottom, 0px))',
    minHeight: '100dvh',
  },
  contentMobile: {
    marginLeft: 0,
    flex: 1,
    padding: '16px',
    paddingBottom: 'calc(16px + env(safe-area-inset-bottom, 0px))',
    minHeight: '100dvh',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '24px',
  },
  h1: {
    margin: 0,
    fontSize: '1.4rem',
    fontWeight: 700,
    color: colors.white,
  },
  card: {
    background: colors.card,
    borderRadius: '12px',
    padding: '20px',
    marginBottom: '16px',
  },
  tableWrap: {
    overflowX: 'auto',
    WebkitOverflowScrolling: 'touch',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    minWidth: '600px',
  },
  th: {
    textAlign: 'left',
    color: colors.muted,
    fontSize: '0.75rem',
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    padding: '8px 12px',
    borderBottom: `1px solid ${colors.border}`,
  },
  td: {
    padding: '12px',
    color: colors.white,
    fontSize: '0.9rem',
    borderBottom: `1px solid rgba(51,51,51,0.5)`,
  },
  trClickable: {
    cursor: 'pointer',
    transition: 'background 0.1s',
  },
  // Use this inline: onPointerEnter + onPointerLeave (replaces mouse events, works on touch)
  trHoverOn: e => { if (e.pointerType !== 'touch') e.currentTarget.style.background = '#1e1e1e'; },
  trHoverOff: e => { e.currentTarget.style.background = 'transparent'; },
  label: {
    color: colors.muted,
    fontSize: '0.8rem',
    fontWeight: 600,
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
  },
  input: {
    background: colors.input,
    border: `1px solid ${colors.border}`,
    borderRadius: '10px',
    color: colors.white,
    fontSize: '1rem',
    padding: '12px 14px',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
    colorScheme: 'dark',
  },
  btn: {
    background: colors.accent,
    border: 'none',
    borderRadius: '10px',
    color: colors.white,
    cursor: 'pointer',
    fontSize: '0.9rem',
    fontWeight: 700,
    padding: '10px 20px',
    transition: 'opacity 0.15s',
  },
  btnSmall: {
    background: colors.accent,
    border: 'none',
    borderRadius: '8px',
    color: colors.white,
    cursor: 'pointer',
    fontSize: '0.8rem',
    fontWeight: 600,
    padding: '6px 14px',
  },
  btnOutline: {
    background: 'transparent',
    border: `1px solid ${colors.border}`,
    borderRadius: '8px',
    color: colors.muted,
    cursor: 'pointer',
    fontSize: '0.8rem',
    fontWeight: 600,
    padding: '6px 14px',
  },
  statRow: {
    display: 'flex',
    gap: '16px',
    flexWrap: 'wrap',
    marginBottom: '20px',
  },
  statCard: {
    background: colors.card,
    borderRadius: '12px',
    padding: '16px 20px',
    flex: 1,
    minWidth: '140px',
  },
  statValue: {
    fontSize: '1.6rem',
    fontWeight: 700,
    color: colors.white,
    margin: 0,
  },
  statLabel: {
    fontSize: '0.75rem',
    color: colors.muted,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    margin: '4px 0 0',
  },
  filterBar: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
    marginBottom: '16px',
    alignItems: 'center',
  },
  filterTab: {
    background: 'transparent',
    border: `1px solid ${colors.border}`,
    borderRadius: '8px',
    color: colors.muted,
    cursor: 'pointer',
    fontSize: '0.8rem',
    fontWeight: 600,
    padding: '8px 14px',
    minHeight: '44px',
    display: 'inline-flex',
    alignItems: 'center',
  },
  filterTabActive: {
    background: colors.accent,
    borderColor: colors.accent,
    color: colors.white,
  },
  pagination: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '12px',
    marginTop: '16px',
  },
  backLink: {
    color: colors.muted,
    fontSize: '0.85rem',
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    padding: '8px',
    margin: '-8px',
    textDecoration: 'underline',
    minHeight: '44px',
    display: 'inline-flex',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: '0.85rem',
    fontWeight: 700,
    color: colors.muted,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    margin: '20px 0 10px',
  },
};
